# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2018
  project: FORM4  Status Monitor
  version: 0.0
  release: 0.0.1
  latex_documents:
  - - Index
    - form4_statusmonitor.tex
    - FORM4  Status Monitor
    - form4 GmbH & Co. KG
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
